exercise_generation:
    description: >
      Generate a math problem for the learner to solve using the math_ex_tool.
    expected_output: >
      Output from the math_ex_tool, where problem is a string representing the math problem and solution is the correct answer.

collect_user_answer:
    description: >
      Collect the user's answer to the math problem using the UserInputTool. Dont show the correct answer in the question.
    expected_output: >
      The learner's answer to the math problem.

answer_evaluation:
    description: >
      Check the learner's answer against the correct answer and provide feedback on their performance.
    expected_output: >
      Feedback on the learner's answer, indicating whether it is correct or incorrect.
